name: Node Build, Testing, Linting & Formatting CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
  
  # - name: npm build
      # run: npm run build --if-present
      
    - name: npm test
      run: npm run test:mocha --if-present
      
    # Static code analysis: Eslint. Checks programmatic and stylistic errors
    - name: lint
    - run: npx eslint . --ext .js,.jsx,.ts,.tsx
   
   # Automated code formatting (all files)
    - name: format
    - run: npx prettier --write .
